### ISSUE TITLE
"update" option has the potential to break an Arch Linux system

### ISSUE THREAD

**Issue by dogknowsnx** [bbedward/pac-pacman-aliases#1]
By issuing that alias one will set an `Arch Linux` system up for a partial upgrade:
https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported

The only time one would want to update a single package before doing a full system upgrade is explained here:
https://wiki.archlinux.org/title/Pacman/Package_signing#Upgrade_system_regularly

Please remove that option ASAP from your script, since it has no use and will potentially break an `Arch Linux` system if not immediately followed by a full system upgrade.

**Comment by bbedward** [comment]
Thanks for the tip, removed it
